[project]
name = "gen-cov-abm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.7",
    "nexusformat>=2.0.0",
    "pandas>=2.3.3",
    "seaborn>=0.13.2",
    "toytree>=3.0.10",
]
