simulation_metadata:
  device: cpu
  num_episodes: 1
  num_steps_per_episode: 10
  num_substeps_per_step: 3

population:
  data_root: "./data/populations"
  folder: "pop25001"

disease:
  data_file: "./data/daily_county_data/25001_daily_data.csv"

substeps:
  make_isolation_decision:
    key: policy
    active_agents: agents
    observation:
      - agents
    update:
      - agents

  new_transmission:
    key: transition
    active_agents: agents
    observation:
      - agents
    update:
      - agents

  seirm_progression:
    key: transition
    active_agents: agents
    observation:
      - agents
    update:
      - agents




state:
  environment: {}
  agents: {}
  objects: {}
  locations: {}
  policies: {}
  network: {}
  active_agents: {}
